// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FoodDelivery.Models
{
    [Table("dishes")]
    public partial class Dish
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        [Required]
        [StringLength(250)]
        public string Description { get; set; }
        public double Price { get; set; }
        [Required]
        [Column("Nutritional values")]
        [StringLength(250)]
        public string NutritionalValues { get; set; }
        [StringLength(100)]
        public string Image { get; set; }
        public bool Vegan { get; set; }
        [Column("restaurant_id")]
        public int RestaurantId { get; set; }

        [ForeignKey("RestaurantId")]
        [InverseProperty("Dishes")]
        public virtual Restaurant Restaurant { get; set; }
    }
}