// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FoodDelivery.Models
{
    [Keyless]
    [Table("order_dishes")]
    public partial class OrderDish
    {
        [Column("id")]
        public int Id { get; set; }

        [Column("id_order")]
        public int IdOrder { get; set; }
        [Column("id_dish")]
        public int IdDish { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }

        [ForeignKey("IdDish")]
        public virtual Dish IdDishNavigation { get; set; }
        [ForeignKey("IdOrder")]
        public virtual Order IdOrderNavigation { get; set; }
    }
}