// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FoodDelivery.Models
{
    [Table("orders")]
    public partial class Order
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("client_id")]
        public int ClientId { get; set; }
        [Column("date_of_order", TypeName = "datetime")]
        public DateTime DateOfOrder { get; set; }
        [Column("rest_id")]
        public int RestId { get; set; }
        [Column("price")]
        public double Price { get; set; }
        [Required]
        [Column("adress_delivered")]
        [StringLength(500)]
        public string AdressDelivered { get; set; }
    }
}