// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FoodDelivery.Models
{
    [Table("user_Details")]
    public partial class UserDetail
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required]
        [StringLength(20)]
        public string PhoneNumber { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateOfBirth { get; set; }
        [Required]
        [StringLength(255)]
        public string Address { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        public bool? Admin { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }
        public string AdditionalAddresses { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("UserDetails")]
        public virtual UserCredential User { get; set; }
    }
}