// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FoodDelivery.Models
{
    [Table("user_Credentials")]
    [Index("Email", Name = "UQ__user_Cre__A9D10534807D6AB2", IsUnique = true)]
    public partial class UserCredential
    {
        public UserCredential()
        {
            UserDetails = new HashSet<UserDetail>();
            UserSessions = new HashSet<UserSession>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [StringLength(128)]
        public string Password { get; set; }
        [Required]
        [MaxLength(64)]
        public byte[] Salt { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual ICollection<UserSession> UserSessions { get; set; }
    }
}